### ISSUE TITLE
新增需求 对标Microsoft Authenticator的安全选项和同步选项

### ISSUE THREAD

**Issue by eveloki** [SoildFaker/ohtotptoken#3]
安全性相关https://github.com/SoildFaker/ohtotptoken/pull/2

账户同步功能能否和Microsoft Authenticator一样同步到微软账户类似同步到华为账户
能力为ohos.data.cloudData (端云服务)

另外想问下为什么要使用腾讯的mmkv？ mmkv没有使用MMKV_MULTI_PROCESS 所以理论上直接替换使用ohos.data.sendablePreferences (共享用户首选项)

- [ ] 使用singlekvstore替换MMKV （单版本分布式键值数据库，不对数据所属设备进行区分，提供查询数据和同步数据的方法）https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/js-apis-distributedkvstore-V5#singlekvstore
- [ ] 单独使用@ohos.security.asset (关键资产存储服务)存储密钥
- [ ] 需要自动化MMKV迁移数据 以保证旧版本兼容性

**Comment by SoildFaker** [comment]
同步华为账号的能力未来会加入，至于为什么用mmkv是因为这个项目一开始只是想简单做一个app，体验一下arkts的开发，而mmkv使用起来相较鸿蒙的kit简单很多。确实，mmkv不是必须的，我会替换掉。

**Comment by eveloki** [comment]
收到  因为这个存储涉及到应用核心逻辑 我就没有提交pr 如果您替换之后需要实现后续的功能  我非常乐意参与

**Comment by eveloki** [comment]
https://gitee.com/harmonyos_samples/hmosworld/blob/master/commons/datastore/src/main/ets/datasource/datastore/PreferenceManager.ets  参照实现

**Comment by SoildFaker** [comment]
设置的存储我用preference实现了，不过令牌的保存就先保持目前的mmkv吧，要么换kvstore；先不着急改。

**Comment by eveloki** [comment]
了解 不急

**Comment by SoildFaker** [comment]
ok，了解，我这两天在外面，后面尽快改掉
