### ISSUE TITLE
item修改逻辑bug

### ISSUE THREAD

**Issue by lsxuan12138** [SoildFaker/ohtotptoken#8]
以下这部分代码的逻辑，会导致在修改item的密钥时，直接多出一个item（因为这里是按照secret匹配的）
![image](https://github.com/user-attachments/assets/70e76f13-d0fc-4992-aa63-3a90ac09e842)

**Comment by lsxuan12138** [comment]
虽然一般也不会修改，但是这个bug确实存在，建议使用uuid之类的作为标识（类似主键？）

**Comment by SoildFaker** [comment]
确实，之前直接拿secret当主键了😅

**Comment by lsxuan12138** [comment]
不太想新开issue，在这里说下吧，这个地方只读取BUFFER_SIZE（目前4096）个字节不会有问题吗？目前我用了4个token，导出来的就已经2000多个字符了，如果文件内容超出了怎么办？不应该是循环的读取然后追加吗？
![image](https://github.com/user-attachments/assets/cea688c5-cd97-4098-a8e0-e8873c7b1de1)
